gg_analytics:
  outputs:
    dev:
      type: duckdb
      path: ../../dev_dbfile.duckdb
      schema: BASE
    prod:
        type: duckdb
        path: ../../prod_dbfile.duckdb
        schema: BASE  
  target: dev