with
CTE_REFERALLS_SOURCE as (
  select *
  from {{ gg_ref('GG_REFERRALS', enable_mock=true) }}
)

, CTE_PARTNER_CONSULTANTS as (
  select
    PARTNER_ID
    , PARTNER_CONSULTANT_ID
    , min(CREATED_AT_DATE_TIME) as FIRST_REFERRAL_DATE_TIME
    , max(CREATED_AT_DATE_TIME) as LAST_REFERRAL_DATE_TIME
  from CTE_REFERALLS_SOURCE
  group by
    PARTNER_ID
    , PARTNER_CONSULTANT_ID
)

, CTE_FINAL as (
  select
    PARTNER_ID
    , PARTNER_CONSULTANT_ID
    , FIRST_REFERRAL_DATE_TIME
    , LAST_REFERRAL_DATE_TIME
  from CTE_PARTNER_CONSULTANTS
)

select *
from CTE_FINAL