with
CTE_PARTNERS_SOURCE as (
  select *
  from {{ ref('GG_PARTNERS') }}
)

, CTE_SALES_CONTACTS_SOURCE as (
  select *
  from {{ ref('SALES_CONTACT') }}
)

, CTE_PARTNER as (
    select
    P.PARTNER_ID
    , P.PARTNER_TYPE
    , SC.SALES_CONTACT_ID as PARTNER_SALES_CONTACT_ID
    , P.PARTNER_SALES_CONTACT_NAME
    , P.CREATED_AT_DATE_TIME
    , P.UPDATED_AT_DATE_TIME
  from CTE_PARTNERS_SOURCE as P
  left join CTE_SALES_CONTACTS_SOURCE as SC
  on P.PARTNER_SALES_CONTACT_NAME = SC.SALES_CONTACT_NAME
)

, CTE_FINAL as (
  select
    PARTNER_ID
    , PARTNER_TYPE
    {# , PARTNER_STATUS #}
    , PARTNER_SALES_CONTACT_ID
    , PARTNER_SALES_CONTACT_NAME
    , CREATED_AT_DATE_TIME
    , UPDATED_AT_DATE_TIME
  from CTE_PARTNER
)

select *
from CTE_FINAL