with
CTE_SALES_CONTACTS_SOURCE as (
  select *
  from {{ ref('GG_SALES_CONTACT') }}
)

, CTE_COUNTRY_SOURCE as (
  select *
  from {{ ref('COUNTRY') }}
)

, CTE_SALES_CONTACTS as (
  select
  row_number() over (
    partition by SC.SALES_CONTACT_NAME, SC.SALES_CONTACT_COUNTRY_NAME
    order by SC.SALES_CONTACT_NAME
  ) as SALES_CONTACT_ID
  , SC.SALES_CONTACT_NAME
  , C.COUNTRY_ID as SALES_CONTACT_COUNTRY_ID
  , SC.SALES_CONTACT_COUNTRY_NAME
  from CTE_SALES_CONTACTS_SOURCE SC
  left join CTE_COUNTRY_SOURCE C
  on SC.SALES_CONTACT_COUNTRY_NAME = C.COUNTRY_NAME
)

, CTE_FINAL as (
  select
    SALES_CONTACT_ID
    , SALES_CONTACT_NAME
    , SALES_CONTACT_COUNTRY_ID
    , SALES_CONTACT_COUNTRY_NAME
  from CTE_SALES_CONTACTS
)

select *
from CTE_FINAL